### ISSUE TITLE
choosenim 0.8.5 update self does not see a future release

### ISSUE THREAD

**Issue by Ivoz** [nim-lang/choosenim#37]
Currently it cannot update itself to 0.8.7, is that some error in the release process?

It seems the response to the URL https://nim-lang.org/choosenim/stable needs to be updated

For now, I can't see it in https://github.com/nim-lang/website/tree/master so I assume it's updated somewhere else

**Comment by PMunch** [comment]
You are correct! There is a small manual step with creating new versions which had been forgotten. I've updated the file to point to the 0.8.7 version now!
