### ISSUE TITLE
Trojan / Malware detected in Windows choosenim installation (0.8.9 x86_64 zip file)

### ISSUE THREAD

**Issue by coderjax** [nim-lang/choosenim#47]
Windows Defender (Windows 11)

Trojan: Win32/Wacatac.B!ml
Details: This program is dangerous and executes commands from an attacker.
File: C:\Users\PC\AppData\Local\Temp\choosenim-extraction\nim-2.2.0\koch.exe

**Comment by ringabout** [comment]
See also https://github.com/nim-lang/Nim/issues/23307
